version: '3'

services:
  web:
    build: .
    ports:
      - "5432:5432"
    depends_on:
      - db
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: AAAaaa111
      POSTGRES_DB: synthese
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  db-data:
