# /***************************************************** 
#   Fichier: docker-compose.yml
#   Contexte: settings de docker-compose pour le projet PlanMe
#   Auteur:  Jessika Longtin et Finnegan Simpson 
#  *****************************************************/
version: '3'

services:
  db:
    image: postgres:latest
    container_name: PlanMe
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: AAAaaa111
      POSTGRES_DB: postgres
    volumes:
      - db-data:/var/lib/postgresql/data
      - ./init:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"

volumes:
  db-data:
